alertmanager:
  alertmanagerSpec:
    image:
      repository: registry.cn-beijing.aliyuncs.com/yunionio/alertmanager
      tag: v0.20.0
grafana:
  additionalDataSources:
  - access: proxy
    isDefault: true
    name: Thanos-Query
    type: prometheus
    url: http://thanos-query.onecloud-monitoring:9090
  adminPassword: prom-operator
  adminUser: admin
  grafana.ini:
    server:
      root_url: https://10.168.26.182/grafana/
      serve_from_sub_path: true
  image:
    repository: registry.cn-beijing.aliyuncs.com/yunionio/grafana
    tag: 6.7.1
  ingress:
    enabled: true
    host: ""
    path: /grafana
    secret:
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIICyjCCAbKgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
        cm5ldGVzMCAXDTIwMTIwOTE4MDUwOFoYDzIxMjAxMTE1MTgwNTA4WjAVMRMwEQYD
        VQQDEwprdWJlcm5ldGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
        uI5BnGksN9wNj3+pkpE0tjiEDhy3uRB3cqIBn/lYyRg1iWjSI3LPjFr2Jnb4zys9
        A7NotIlFsLzyXXb90cVjK+yRIe0i1wyIaixWxJnPc7aZ9H1z0F0shjwMrE8Zpj3m
        JZIn4L7TQcSFdg6Cc7SIozC9BOarjKKxK79oiqKNniMHl+zYQcLqPbXsxMbEb/XY
        vXfH8ZJNcvcZCpKHT9GotMO8QOGx4g3qu7TKxq5/xmiIiqgT9CjVg3iZqaRbta1H
        zlaqgTtlcqLDDvBnheyI5FS+KmeaRp2sNm5Ynv2JFv57srMNOlPU7Guqh1iWPcMh
        YdCtg3fJn0AgbGJxktacgwIDAQABoyMwITAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0T
        AQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAqXO+ekNul+dqxlWqgScNsfCA
        oeRQSnYQd/2FyfVWr0zmVliABgIERVq5RS4Bwl53SSl6mm9+rmpc5ZZ0qSN+re1D
        EgX60dBRo4CGhRcE8lCDg5pRo8DF0Ik+somSTE9r2NadjMGHdkXUm9CEQ1G+7wMN
        s+bHf1LtEXHxw5INV3l0ozdmrmlK7zWmeJSM9uGteAqD+2b39Rc996seGH8W+QF3
        J2wR359oFrdp3D0R7wpCgRoEnRmoHUOyjiIsSMA1c9ubA7bMuP7FejHBf3NPjeR0
        bHWHmeBv265DH3k0a734777NcYizDFDn+hxhX30x05ac3cdRdx80Bt+zklpTPQ==
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpQIBAAKCAQEAuI5BnGksN9wNj3+pkpE0tjiEDhy3uRB3cqIBn/lYyRg1iWjS
        I3LPjFr2Jnb4zys9A7NotIlFsLzyXXb90cVjK+yRIe0i1wyIaixWxJnPc7aZ9H1z
        0F0shjwMrE8Zpj3mJZIn4L7TQcSFdg6Cc7SIozC9BOarjKKxK79oiqKNniMHl+zY
        QcLqPbXsxMbEb/XYvXfH8ZJNcvcZCpKHT9GotMO8QOGx4g3qu7TKxq5/xmiIiqgT
        9CjVg3iZqaRbta1HzlaqgTtlcqLDDvBnheyI5FS+KmeaRp2sNm5Ynv2JFv57srMN
        OlPU7Guqh1iWPcMhYdCtg3fJn0AgbGJxktacgwIDAQABAoIBAC9Ed/doVGPmHy7+
        gl7Ag+Cbru6yWjeyyPT6GzJuuVeftK6BwzhDAncvINYPKIBe0ZyuCYYbllbCvcxE
        WpOsW073ouAujPrJAfM3ce2eeyxmux2MN+pIwsuKe7Bx/d6/Ab/jpAUCuragb5Ih
        +zVJKqmpJPApaAx36qqKtmqzYVP7s09R8Y8eneaBw1NE9F1pM3aqLrUPqGp4uTdi
        t7gT8s/l59BIPyhRczT76ZmJmj1udeR70jc5SRK4SS02knYLZ9umSTXHbDRdCoNS
        b1N2gmtwrtbCYZy8SMhhNo8CA1IUBE0UgZbKLmIUMr1TpcYOdqT1VIGvSZkYfH5w
        2vuKgzkCgYEA5FUjdZRyx63vhEZpPuwMlrqZTZr+mH2g+18q/NJdApwsyVhRM6tx
        99DgHNpcziYtfvIN027pQZPoSMsJJcnGjRU+O6/rjHH9GdkyzR2Q0mx7YyRKSiH6
        AJUh/HRfSBqC0sT1dhny2onCnSZRwM9zVQ3D5f9Gdb9A4vE6SlR7efcCgYEAzusp
        ZZbQZs+ngsGuntfBpqyv4NNz0tG4tS2rm5chHep1H/1aAdecu+XTjp6ngN2bqtpy
        1LiAcFp87ruALJ+wxTM6nTZcL8HtpqRgmoQWn9H0YJlphSvqfdGtQU4KCF7Z+H7R
        XJIVdtXc6S2+mZ5CbU3AWI9YRrT4fWrY8ddebtUCgYEAj/aiQdtUN1QSpVrjttmL
        4mlKiWTFS45CNtu9NeTI4gFoN5bos+RQGkjnVSnUw+HMY7LoRrwyc7d3CJaDcQD0
        oDWZpHZ51HZ2d5q7bhpLGnFtpofWE0Gy6DUfVZZmEQcuHwgyH8GinmmnfAASIbhq
        5mCkeFpoqYrptW0VLJJxu+cCgYEAw1wb9aJymN8t1LJw39/tIiSg2bBLBpyju8um
        3nvN9KTMeKuHM34SqQTQvTLmCzEwLBubl2OrQGju06eL2JXdHBLGIHCWkTCT5GYG
        H1zez343MI0np2hTOP+iiKnZpxWGzqtNmA0E3vIEZNOfxQI6zWA/Xl3YhsmOYzti
        INOqgRECgYEAwcVbdhkkMyrZyzN3uD07WXj+zvCmjn1q6jeXRSTNPrQliuL22SNk
        7Oyu+fANwL0+eloqAGdFIhPXqX799sDWaeMY3MbsjjrkZrssp+ZqdWA/90PAyX+6
        FfyBC1i8jJx8nyfDr21kjZdzlSwH0Dr5x38yNODTSjBYICOjm964H34=
        -----END RSA PRIVATE KEY-----
      name: grafana-ingress-tls
    tls:
    - secretName: grafana-ingress-tls
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 1Gi
    type: pvc
  service:
    type: ClusterIP
  sidecar:
    datasources:
      defaultDatasourceEnabled: false
    image:
      repository: registry.cn-beijing.aliyuncs.com/yunionio/k8s-sidecar
      tag: 0.1.99
kube-state-metrics:
  image:
    repository: registry.cn-beijing.aliyuncs.com/yunionio/kube-state-metrics
    tag: v1.9.4
loki:
  alerting_groups:
  - name: example
    # rules:
    # - alert: HighThroughputLogStreams
      # expr: sum by(container) (rate({job=~"onecloud/.*"}[1m])) > 1
      # for: 3s
  - name: log_notification
    rules:
    - alert: 错误日志
      annotations:
        description: "{{ $labels.mark }}{{ $labels.msg }}"
        hostname: "{{ $labels.hostname }}"
      expr: 'count_over_time({job=~"onecloud/.*"} |~ `^\[E\s` | regexp `\[(?P<mark>.*)\]\s(?P<msg>.*)` [10s]) > 0'
      for: 0
      labels:
        severity: error
        from: loki
  config:
    compactor:
      shared_store: s3
    schema_config:
      configs:
      - from: "2020-10-24"
        index:
          period: 24h
          prefix: index_
        object_store: aws
        schema: v11
        store: boltdb-shipper
    storage_config:
      aws:
        s3: s3://testadmin:test@test@minio.onecloud-minio:9000/loki
        s3forcepathstyle: true
      boltdb_shipper:
        cache_ttl: 24h
        shared_store: s3
    ruler:
      storage:
        type: local
        local:
          directory: /rules
      rule_path: /tmp/scratch
      alertmanager_url: http://monitor-monitor-stack-alertmanager:9093
      ring:
        kvstore:
          store: inmemory
      enable_api: true
  image:
    repository: registry.cn-beijing.aliyuncs.com/yunionio/loki
    tag: 2.0.0
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 49Gi
    type: pvc
prometheus:
  prometheusSpec:
    image:
      repository: registry.cn-beijing.aliyuncs.com/yunionio/prometheus
      tag: v2.15.2
    retention: 4h
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    thanos:
      baseImage: registry.cn-beijing.aliyuncs.com/yunionio/thanos
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objstore-config
      version: v0.16.0
prometheus-node-exporter:
  image:
    repository: registry.cn-beijing.aliyuncs.com/yunionio/node-exporter
    tag: v0.18.1
prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
      image:
        repository: registry.cn-beijing.aliyuncs.com/yunionio/kube-webhook-certgen
        tag: v1.0.0
  configmapReloadImage:
    repository: registry.cn-beijing.aliyuncs.com/yunionio/configmap-reload
    tag: v0.0.1
  image:
    repository: registry.cn-beijing.aliyuncs.com/yunionio/prometheus-operator
    tag: v0.37.0
  prometheusConfigReloaderImage:
    repository: registry.cn-beijing.aliyuncs.com/yunionio/prometheus-config-reloader
    tag: v0.37.0
  tlsProxy:
    enabled: false
    image:
      repository: registry.cn-beijing.aliyuncs.com/yunionio/ghostunnel
      tag: v1.5.2
promtail:
  image:
    repository: registry.cn-beijing.aliyuncs.com/yunionio/promtail
    tag: 2.0.0
  extraCommandlineArgs:
    - -client.external-labels=hostname=$(HOSTNAME)

alertmanager:

  ## Deploy alertmanager
  ##
  enabled: true

  ## Api that prometheus will use to communicate with alertmanager. Possible values are v1, v2
  ##
  apiVersion: v2

  ## Service account for Alertmanager to use.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  ##
  serviceAccount:
    create: true
    name: ""

  ## Configure pod disruption budgets for Alertmanager
  ## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
  ## This configuration is immutable once created and will require the PDB to be deleted to be changed
  ## https://github.com/kubernetes/kubernetes/issues/45398
  ##
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable: ""

  ## Alertmanager configuration directives
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
  ##
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      # group_interval: 5m
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'ops'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'ops'
    receivers:
    - name: 'ops'
      webhook_configs:
        # - url: https://oapi.dingtalk.com/robot/send?access_token=63270908ee2ce7d6c8b9f8d19d040a7dc97aeb1fb970d67e12213f235e6f89ec
        - url: http://10.168.26.182:8081/prometheus/alert
          send_resolved: false

  ## Pass the Alertmanager configuration directives through Helm's templating
  ## engine. If the Alertmanager configuration contains Alertmanager templates,
  ## they'll need to be properly escaped so that they are not interpreted by
  ## Helm
  ## ref: https://helm.sh/docs/developing_charts/#using-the-tpl-function
  ##      https://prometheus.io/docs/alerting/configuration/#%3Ctmpl_string%3E
  ##      https://prometheus.io/docs/alerting/notifications/
  ##      https://prometheus.io/docs/alerting/notification_examples/
  tplConfig: false

  ## Alertmanager template files to format alerts
  ## ref: https://prometheus.io/docs/alerting/notifications/
  ##      https://prometheus.io/docs/alerting/notification_examples/
  ##
  # templateFiles:
  ## An example template:
    # template_1.tmpl: |-
        # {{ define "cluster" }}{{ .ExternalURL | reReplaceAll ".*alertmanager\\.(.*)" "$1" }}{{ end }}
        # {{ define "slack.myorg.text" }}
        # {{- $root := . -}}
        # {{ range .Alerts }}
          # *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
          # *Cluster:*  {{ template "cluster" $root }}
          # *Description:* {{ .Annotations.description }}
          # *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
          # *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
          # *Details:*
            # {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            # {{ end }}

additionalPrometheusRules: []
 # - name: my-rule-file
   # groups:
     # - name: my_group
       # rules:
        # - alert: 主机状态
          # expr: up == 1
          # for: 15s
          # labels:
            # status: warning
          # annotations:
            # summary: "{{$labels.instance}}:服务器关闭"
            # description: "{{$labels.instance}}:服务器关闭"
